# Generated by Django 2.2 on 2020-05-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='plan',
            new_name='how_mutch_time',
        ),
        migrations.RenameField(
            model_name='watershare',
            old_name='plan',
            new_name='how_mutch_time',
        ),
        migrations.AddField(
            model_name='growbox',
            name='_DHT22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.DHT22'),
        ),
        migrations.AddField(
            model_name='growbox',
            name='_WaterShare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.WaterShare'),
        ),
        migrations.AddField(
            model_name='growbox',
            name='_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Light'),
        ),
        migrations.AddField(
            model_name='light',
            name='turn_on_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watershare',
            name='turn_on_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dht22',
            name='humidity',
            field=models.FloatField(blank=True, default=0, null=None),
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ident', models.IntegerField(default=0)),
                ('_temperature', models.FloatField(blank=True, default=0, null=None)),
                ('grow_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.GrowBox')),
            ],
        ),
        migrations.CreateModel(
            name='humidity_of_earth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ident', models.IntegerField(default=0)),
                ('humidity', models.FloatField(blank=True, default=0, null=None)),
                ('grow_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.GrowBox')),
            ],
        ),
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ident', models.IntegerField(default=0)),
                ('cou2_proc', models.FloatField(blank=True, default=0, null=None)),
                ('grow_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.GrowBox')),
            ],
        ),
        migrations.AddField(
            model_name='growbox',
            name='_CO2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.CO2'),
        ),
        migrations.AddField(
            model_name='growbox',
            name='_humidity_of_earth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.humidity_of_earth'),
        ),
        migrations.AddField(
            model_name='growbox',
            name='_temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.temperature'),
        ),
    ]
